-- Durable instance-seal reconciliation. Provider and validator credentials,
-- private-key references, and raw remote messages never enter these tables.
-- Existing rows remain NULL and therefore cannot be selected for sealing;
-- only a publisher that knows the exact generated byte length may populate it.
ALTER TABLE completion_artifact_pdf
ADD COLUMN pdf_byte_size integer
CHECK (pdf_byte_size IS NULL OR pdf_byte_size BETWEEN 1 AND 33554432);

CREATE TABLE pdf_seal_job (
  id text NOT NULL PRIMARY KEY,
  envelope_id text NOT NULL UNIQUE REFERENCES completion_artifact_pdf(envelope_id),
  operation_id text NOT NULL UNIQUE,
  validation_id text NOT NULL UNIQUE,
  status text NOT NULL CHECK (status IN ('pending','processing','failed','publication_ready')),
  next_action text NOT NULL CHECK (next_action IN ('submit','recover_submit','poll_provider','validate','publish')),
  claim_token text,
  attempt_sequence integer NOT NULL DEFAULT 0 CHECK (attempt_sequence BETWEEN 0 AND 2147483647),
  retry_failures integer NOT NULL DEFAULT 0 CHECK (retry_failures BETWEEN 0 AND 8),
  available_at timestamptz NOT NULL,
  locked_at timestamptz,
  retryable boolean,
  last_error_code text,
  source_object_key text NOT NULL,
  source_sha256 text NOT NULL,
  source_byte_size integer NOT NULL CHECK (source_byte_size BETWEEN 1 AND 33554432),
  requested_profile text NOT NULL CHECK (requested_profile IN ('pades-b-b','pades-b-t')),
  signer_certificate_sha256 text NOT NULL,
  seal_policy_id text NOT NULL,
  validation_policy_id text NOT NULL,
  tsa_policy_id text,
  tsa_trust_bundle_sha256 text,
  provider_receipt_id text,
  sealed_object_key text,
  sealed_sha256 text,
  sealed_byte_size integer,
  achieved_profile text,
  validator_receipt_id text,
  validation_checks_json text,
  validation_report_object_key text,
  validation_report_sha256 text,
  validation_report_byte_size integer,
  validated_at timestamptz,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  ready_at timestamptz,
  failed_at timestamptz,
  CONSTRAINT pdf_seal_job_id_uuidv7 CHECK (
    id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
  ),
  CONSTRAINT pdf_seal_job_operation_uuidv7 CHECK (
    operation_id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
  ),
  CONSTRAINT pdf_seal_job_validation_uuidv7 CHECK (
    validation_id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
  ),
  CONSTRAINT pdf_seal_job_digest_shapes CHECK (
    source_sha256 ~ '^[0-9a-f]{64}$'
    AND signer_certificate_sha256 ~ '^[0-9a-f]{64}$'
    AND (tsa_trust_bundle_sha256 IS NULL OR tsa_trust_bundle_sha256 ~ '^[0-9a-f]{64}$')
    AND (sealed_sha256 IS NULL OR sealed_sha256 ~ '^[0-9a-f]{64}$')
    AND (validation_report_sha256 IS NULL OR validation_report_sha256 ~ '^[0-9a-f]{64}$')
  ),
  CONSTRAINT pdf_seal_job_policy_tuple CHECK (
    (requested_profile = 'pades-b-b' AND tsa_policy_id IS NULL
      AND tsa_trust_bundle_sha256 IS NULL)
    OR (requested_profile = 'pades-b-t' AND tsa_policy_id IS NOT NULL
      AND tsa_trust_bundle_sha256 IS NOT NULL)
  ),
  CONSTRAINT pdf_seal_job_lease_state CHECK (
    (status = 'processing' AND claim_token IS NOT NULL AND locked_at IS NOT NULL)
    OR (status <> 'processing' AND claim_token IS NULL AND locked_at IS NULL)
  ),
  CONSTRAINT pdf_seal_job_failure_state CHECK (
    (status = 'failed' AND retryable IS NOT NULL AND last_error_code IS NOT NULL
      AND ready_at IS NULL AND ((retryable AND retry_failures BETWEEN 1 AND 7
        AND failed_at IS NULL)
      OR (NOT retryable AND failed_at IS NOT NULL)))
    OR (status <> 'failed' AND retryable IS NULL AND last_error_code IS NULL AND failed_at IS NULL)
  ),
  CONSTRAINT pdf_seal_job_action_evidence CHECK (
    (next_action IN ('submit','recover_submit') AND provider_receipt_id IS NULL
      AND sealed_object_key IS NULL AND sealed_sha256 IS NULL AND sealed_byte_size IS NULL
      AND achieved_profile IS NULL AND validator_receipt_id IS NULL
      AND validation_checks_json IS NULL AND validation_report_object_key IS NULL
      AND validation_report_sha256 IS NULL AND validation_report_byte_size IS NULL
      AND validated_at IS NULL AND ready_at IS NULL)
    OR (next_action = 'poll_provider' AND provider_receipt_id IS NOT NULL
      AND sealed_object_key IS NULL AND sealed_sha256 IS NULL AND sealed_byte_size IS NULL
      AND achieved_profile IS NULL AND validator_receipt_id IS NULL
      AND validation_checks_json IS NULL AND validation_report_object_key IS NULL
      AND validation_report_sha256 IS NULL AND validation_report_byte_size IS NULL
      AND validated_at IS NULL AND ready_at IS NULL)
    OR (next_action = 'validate' AND provider_receipt_id IS NOT NULL
      AND sealed_object_key IS NOT NULL AND sealed_sha256 IS NOT NULL
      AND sealed_byte_size > source_byte_size AND sealed_byte_size <= 67108864
      AND achieved_profile = requested_profile AND validator_receipt_id IS NULL
      AND validation_checks_json IS NULL AND validation_report_object_key IS NULL
      AND validation_report_sha256 IS NULL AND validation_report_byte_size IS NULL
      AND validated_at IS NULL AND ready_at IS NULL)
    OR (next_action = 'publish' AND status = 'publication_ready'
      AND provider_receipt_id IS NOT NULL AND sealed_object_key IS NOT NULL
      AND sealed_sha256 IS NOT NULL AND sealed_byte_size > source_byte_size
      AND sealed_byte_size <= 67108864 AND achieved_profile = requested_profile
      AND validator_receipt_id IS NOT NULL AND validation_checks_json IS NOT NULL
      AND length(validation_checks_json) BETWEEN 2 AND 32768
      AND validation_report_object_key IS NOT NULL
      AND validation_report_sha256 IS NOT NULL
      AND validation_report_byte_size BETWEEN 1 AND 65536
      AND validated_at IS NOT NULL AND ready_at IS NOT NULL)
  ),
  CONSTRAINT pdf_seal_job_publish_state CHECK (
    (status = 'publication_ready' AND next_action = 'publish')
    OR (status <> 'publication_ready' AND next_action <> 'publish')
  ),
  CONSTRAINT pdf_seal_job_safe_lengths CHECK (
    length(source_object_key) BETWEEN 1 AND 1024
    AND length(seal_policy_id) BETWEEN 1 AND 128
    AND length(validation_policy_id) BETWEEN 1 AND 128
    AND (tsa_policy_id IS NULL OR length(tsa_policy_id) BETWEEN 1 AND 128)
    AND (provider_receipt_id IS NULL OR length(provider_receipt_id) BETWEEN 1 AND 256)
    AND (validator_receipt_id IS NULL OR length(validator_receipt_id) BETWEEN 1 AND 256)
    AND (last_error_code IS NULL OR length(last_error_code) BETWEEN 2 AND 65)
  )
);

CREATE INDEX pdf_seal_job_claim
  ON pdf_seal_job(status, available_at, created_at, id)
  WHERE status IN ('pending','failed');

CREATE INDEX pdf_seal_job_reclaim
  ON pdf_seal_job(locked_at, created_at, id)
  WHERE status = 'processing';

CREATE TABLE pdf_seal_attempt (
  id text NOT NULL PRIMARY KEY,
  job_id text NOT NULL REFERENCES pdf_seal_job(id),
  attempt_number integer NOT NULL CHECK (attempt_number BETWEEN 1 AND 2147483647),
  action text NOT NULL CHECK (action IN ('submit','recover_submit','poll_provider','validate')),
  outcome text NOT NULL CHECK (outcome IN (
    'ambiguous','checkpointed','deferred','publication_ready',
    'retryable_failed','permanently_failed'
  )),
  error_code text,
  provider_receipt_id text,
  validator_receipt_id text,
  sealed_sha256 text,
  started_at timestamptz NOT NULL,
  finished_at timestamptz NOT NULL,
  UNIQUE (job_id, attempt_number),
  CONSTRAINT pdf_seal_attempt_id_uuidv7 CHECK (
    id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
  ),
  CONSTRAINT pdf_seal_attempt_outcome_shape CHECK (
    (outcome IN ('retryable_failed','permanently_failed') AND error_code IS NOT NULL)
    OR (outcome NOT IN ('retryable_failed','permanently_failed') AND error_code IS NULL)
  ),
  CONSTRAINT pdf_seal_attempt_time_order CHECK (finished_at >= started_at)
);

CREATE FUNCTION reject_pdf_seal_attempt_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'pdf seal attempts are immutable';
END;
$$;

CREATE TRIGGER pdf_seal_attempt_no_update_or_delete
BEFORE UPDATE OR DELETE ON pdf_seal_attempt
FOR EACH ROW EXECUTE FUNCTION reject_pdf_seal_attempt_mutation();
